config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/dashboard', to: 'dashboard#index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  resources :plots
  devise_for :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_many :plots
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plot.rb
# frozen_string_literal: true

class Plot < ApplicationRecord
  belongs_to :account
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username first_name last_name])
    devise_parameter_sanitizer.permit(:update, keys: %i[username first_name last_name url])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end

  def properties; end

  def reports; end
end

app/controllers/plots_controller.rb
# frozen_string_literal: true

class PlotsController < ApplicationController
  before_action :set_plot, only: %i[show edit update destroy]

  # GET /plots
  # GET /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1
  # GET /plots/1.json
  def show; end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit; end

  # POST /plots
  # POST /plots.json
  def create
    @plot = Plot.new(plot_params)

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: 'Plot was successfully created.' }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1
  # PATCH/PUT /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: 'Plot was successfully updated.' }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1
  # DELETE /plots/1.json
  def destroy
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: 'Plot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_plot
    @plot = Plot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def plot_params
    params.require(:plot).permit(:name, :address, :price, :rooms, :bathrooms, :photo, :photo_cache)
  end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ApplicationController
  def main; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/plots_helper.rb
# frozen_string_literal: true

module PlotsHelper
end

app/helpers/public_helper.rb
# frozen_string_literal: true

module PublicHelper
end

app/views/dashboard/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
      <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
          stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
          class="feather feather-calendar">
          <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
          <line x1="16" y1="2" x2="16" y2="6"></line>
          <line x1="8" y1="2" x2="8" y2="6"></line>
          <line x1="3" y1="10" x2="21" y2="10"></line>
        </svg>
        This week
      </button>
    </div>
  </div>
  
  <h2>Section title</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Header</th>
          <th>Header</th>
          <th>Header</th>
          <th>Header</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1,001</td>
          <td>Lorem</td>
          <td>ipsum</td>
          <td>dolor</td>
          <td>sit</td>
        </tr>
        <tr>
          <td>1,002</td>
          <td>amet</td>
          <td>consectetur</td>
          <td>adipiscing</td>
          <td>elit</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>Integer</td>
          <td>nec</td>
          <td>odio</td>
          <td>Praesent</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>libero</td>
          <td>Sed</td>
          <td>cursus</td>
          <td>ante</td>
        </tr>
        <tr>
          <td>1,004</td>
          <td>dapibus</td>
          <td>diam</td>
          <td>Sed</td>
          <td>nisi</td>
        </tr>
      </tbody>
    </table>
  </div>
</main>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Property Finder.</span>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

  <title>Property</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', 'devise', 'dashboard', media:
          'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body id="<%= controller.controller_name%>" class="<%= controller.action_name%>">
  <% if ["public" ,"devise", "sessions"].include?(controller.controller_name) %>
  <header>
    <%= render 'layouts/nav/public' %>
    <%= yield %>
  </header>

  <% else %>
    
    <%= render 'layouts/nav/dashboard' %>
    <div class="container-fluid">
      <div class="row">
        <%= render"layouts/nav/sidebar" %>
        <%= yield %>
      </div>
    </div>
  <% end %>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>

</body>

</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Property Finder</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log Out", destroy_account_session_path, class: "nav-link", method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="/">Property Finder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
      <% if account_signed_in? %>
      <li class="nav-item active">
          <a href="/dashboard" class="nav-link">Dashboard</a>
      </li>
      <% else %>

      <% end %>
        <li class="nav-item active">
          <a href="#" class="nav-link">Latest</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Advertising</a>
        </li>
      <% if account_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_account_session_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/accounts/sign_in" class="nav-link"><span>Log In</span></a>
        </li>
        <li class="nav-item">
          <a href="/accounts/sign_up" class="nav-link"><span>Sign Up</span></a>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
 <nav class="col-md-2 d-none d-md-block pt-5 bg-light sidebar">

      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="/dashboard">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0
                  1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15
                  12 15 22"></polyline></svg>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/plots">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2
                  2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2
                  13 9 20 9"></polyline></svg>
              Plots
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-shopping-cart"><circle cx="9" cy="21"
                  r="1"></circle><circle cx="20" cy="21" r="1"></circle><path
                  d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23
                  6H6"></path></svg>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-users"><path d="M17 21v-2a4 4 0 0
                  0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path
                  d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0
                  0 1 0 7.75"></path></svg>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-bar-chart-2"><line x1="18" y1="20"
                  x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line
                  x1="6" y1="20" x2="6" y2="14"></line></svg>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-layers"><polygon points="12 2 2 7 12 12
                  22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline
                  points="2 12 12 17 22 12"></polyline></svg>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between
          align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#"
            aria-label="Add a new report">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
              viewBox="0 0 24 24" fill="none" stroke="currentColor"
              stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
              class="feather feather-plus-circle"><circle cx="12" cy="12"
                r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line
                x1="8" y1="12" x2="16" y2="12"></line></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2
                  2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline
                  points="14 2 14 8 20 8"></polyline><line x1="16" y1="13"
                  x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline
                  points="10 9 9 9 8 9"></polyline></svg>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2
                  2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline
                  points="14 2 14 8 20 8"></polyline><line x1="16" y1="13"
                  x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline
                  points="10 9 9 9 8 9"></polyline></svg>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2
                  2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline
                  points="14 2 14 8 20 8"></polyline><line x1="16" y1="13"
                  x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline
                  points="10 9 9 9 8 9"></polyline></svg>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2
                  2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline
                  points="14 2 14 8 20 8"></polyline><line x1="16" y1="13"
                  x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline
                  points="10 9 9 9 8 9"></polyline></svg>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/plots/_form.html.erb
<div class="row">
  <%= simple_form_for(@plot) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, class: "form-control", id: "inputText6", placeholder: "Name" %>
      <%= f.input :address, class: "form-control", id: "inputText6", placeholder: "Address" %>
      <%= f.input :price, class: "form-control", id: "inputInteger6", placeholder: "Price" %>
      <%= f.input :rooms, class: "form-control", id: "inputInteger6", placeholder: "Rooms" %>
      <%= f.input :bathrooms, class: "form-control", id: "inputInteger6", placeholder: "Bathrooms" %>
      <%= f.input :photo, class: "form-control", id: "inputImage6", placeholder: "Photo" %>
      <%= f.hidden_field :photo_cache, class: "form-control", id: "inputInteger6", placeholder: "Photo" %><br>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-lg btn-primary btn-block", type: "submit" %>
    </div>
  <% end %>
</div>

app/views/plots/edit.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    
    <h1 class="h2">Editing Plot</h1>
  </div>


        <%= render 'form', plot: @plot %>
        <br>
        <%= link_to 'Show', @plot, class: "btn btn-outline-primary" %> |
        <%= link_to 'Back', plots_path, class: "btn btn-outline-success" %>
</main>

app/views/plots/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    
    <h1 class="h2">Plots</h1>
  </div>

    <div class="table-responsive">
    <table class="table table-striped">
      <thead class="thead-white">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Price</th>
          <th scope="col">Rooms</th>
          <th scope="col">Bathrooms</th>
          
        </tr>
      </thead>

      <tbody>
        <% @plots.each do |plot| %>
          <tr>
            <td scope="row"><%= plot.name %></td>
            <td><%= plot.address %></td>
            <td><%= plot.price %></td>
            <td><%= plot.rooms %></td>
            <td><%= plot.bathrooms %></td>
            <td><%= link_to 'Show', plot %></td>
            <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
            <td><%= link_to 'Destroy', plot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Plot', new_plot_path, class:"btn btn-outline-primary" %>

  </div>
  
</main>

app/views/plots/new.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    
    <h1 class="h2">New Plot</h1>
  </div>

    <div class="table-responsive">
    <table class="table table-striped table-sm">

<%= render 'form', plot: @plot %>

<%= link_to 'Back', plots_path %>

app/views/plots/show.html.erb
 <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    
    <h1 class="h2">Plots</h1>
  </div>

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @plot.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @plot.address %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @plot.price %>
    </p>

    <p>
      <strong>Rooms:</strong>
      <%= @plot.rooms %>
    </p>

    <p>
      <strong>Bathrooms:</strong>
      <%= @plot.bathrooms %>
    </p>

    <%= link_to 'Edit', edit_plot_path(@plot), class: "btn btn-outline-primary"%> |
    <%= link_to 'Back', plots_path, class: "btn btn-outline-success" %>
  </div>
</div>
</main>